tk_welcome_homepage:
    pattern:  /
    defaults: { _controller: TkWelcomeBundle:Default:index }

tk_welcome_summary:
    pattern: /summary/{id}/{token}
    defaults: { _controller: TkWelcomeBundle:Summary:summary }

tk_welcome_choose_member:
    pattern: /invitation/{id}/{token}
    defaults: { _controller: TkWelcomeBundle:Invitation:chooseMember }

tk_welcome_chosen_member:
    pattern: /invitation/chosen/{id}/{token}
    defaults: { _controller: TkWelcomeBundle:Invitation:chosenMember }

tk_welcome_invitation_login:
    pattern:  /login/{id}/{token}
    defaults: { _controller: TkWelcomeBundle:Invitation:invitationLogin }

tk_welcome_register:
    pattern: /register
    defaults: { _controller: TkWelcomeBundle:Default:register }

tk_welcome_subscribe:
    pattern: /subscribe
    defaults: { _controller: TkWelcomeBundle:Default:subscribe }
