tk_expense_homepage:
    pattern:  /expenses
    defaults: { _controller: TkExpenseBundle:Expense:index }

tk_expense_new:
    pattern:  /expenses/new
    defaults: { _controller: TkExpenseBundle:Expense:new }

tk_expense_remove:
    pattern:  /expenses/remove/{id}
    defaults: { _controller: TkExpenseBundle:Expense:remove }
