tk_user_homepage:
    pattern:  /user
    defaults: { _controller: TkUserBundle:Profile:index }

root:
    pattern: /register/confirmed
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true
