tk_user_homepage:
    pattern:  /user
    defaults: { _controller: TkUserBundle:Profile:index }

tk_user_profile_edit:
    pattern:  /user/profile/edit/{id}
    defaults: { _controller: TkUserBundle:Profile:edit }

tk_user_username_edit:
    pattern:  /user/username/edit/{id}
    defaults: { _controller: TkUserBundle:Profile:editUsername }


