tk_group_homepage:
    pattern:  /settings
    defaults: { _controller: TkGroupBundle:Default:index }

tk_group_switch_member:
    pattern:  /switch/{id}
    defaults: { _controller: TkGroupBundle:Default:switch }

tk_group_goto_member:
    pattern:  /goto/{id}
    defaults: { _controller: TkGroupBundle:Default:goTo }

tk_group_new:
    pattern:  /new
    defaults: { _controller: TkGroupBundle:Default:new }

tk_group_add_members:
    pattern:  /add
    defaults: { _controller: TkGroupBundle:Default:addMembers }

tk_group_add_members_success:
    pattern:  /add/invite/
    defaults: { _controller: TkGroupBundle:Default:inviteUser }

tk_group_send_email:
    pattern:  /add/invite/email/
    defaults: { _controller: TkGroupBundle:Default:sendInvitationEmail }