tk_group_homepage:
    pattern:  /default
    defaults: { _controller: TkGroupBundle:Default:index }

tk_group_settings:
    pattern:  /settings
    defaults: { _controller: TkGroupBundle:Setting:index }